import type { Locale } from "@/i18n/config";
import { SITE_CONTACT } from "@/config/site-contact";
import { SITE_GEO } from "@/config/site-location";

const shared = [
  SITE_CONTACT.businessName,
  "Stars Peak",
  SITE_GEO.settlement,
  SITE_GEO.mountain,
  SITE_GEO.naturePark,
  SITE_GEO.locality,
  "Došen Dabar",
  SITE_GEO.administrativeArea,
  SITE_GEO.countryName,
  SITE_GEO.countryNameHr,
] as const;

const byLocale: Record<Locale, readonly string[]> = {
  en: [
    ...shared,
    "Velebit mountain chalet",
    "Stars Peak Velebit",
    "www.velebit-starspeak.com",
    "mountain cabin Velebit",
    "mountain chalet Croatia",
    "luxury mountain retreat Croatia",
    "off-grid holiday house Croatia",
    "off grid cabin Croatia",
    "remote cabin Croatia",
    "Velebit holiday home",
    "vacation rental Velebit",
    "mountain accommodation Croatia",
    "hiking Velebit",
    "hiking accommodation Velebit",
    "Velebit hiking holidays",
    "Premužić trail accommodation",
    "things to do on Velebit",
    "stargazing Velebit",
    "dark sky accommodation Croatia",
    "dark sky Croatia",
    "remote work mountain cabin",
    "digital nomad Croatia nature",
    "photography retreat Velebit",
    "Bačić Duliba accommodation",
    "Karlobag mountains",
    "Baške Oštarije",
    "Northern Velebit",
    "holiday home Croatia",
  ],
  hr: [
    ...shared,
    "planinska kuća Velebit",
    "planinska kuća za odmor",
    "off-grid kuća Hrvatska",
    "smještaj Velebit",
    "kuća za odmor Hrvatska",
    "Velebit smještaj",
    "smještaj Bačić Duliba",
    "planinarenje Velebit",
    "planinarski smještaj Velebit",
    "Premužićeva staza smještaj",
    "što raditi na Velebitu",
    "promatranje zvijezda Velebit",
    "dark sky Hrvatska",
    "remote work Velebit",
    "fotografski retreat Velebit",
    "odmor na Velebitu",
    "planinska kuća Karlobag",
    "Baške Oštarije smještaj",
    "Park prirode Velebit",
  ],
  de: [
    ...shared,
    "Berghütte Velebit",
    "Ferienhaus Velebit",
    "Unterkunft Velebit",
    "Urlaub am Velebit",
    "Wandern Velebit",
    "Ferienhaus Kroatien",
    "Berghütte Kroatien",
    "Unterkunft Bačić Duliba",
    "Karlobag Ferienhaus",
  ],
  fr: [
    ...shared,
    "chalet montagne Velebit",
    "maison vacances Velebit",
    "hébergement Velebit",
    "location Croatie montagne",
    "randonnée Velebit",
    "hébergement Bačić Duliba",
    "Karlobag montagne",
  ],
  it: [
    ...shared,
    "chalet montagna Velebit",
    "casa vacanze Velebit",
    "alloggio Velebit",
    "vacanza montagna Croazia",
    "escursionismo Velebit",
    "alloggio Bačić Duliba",
    "Karlobag montagna",
  ],
};

export function getSeoKeywords(locale: Locale): string[] {
  return [...new Set(byLocale[locale])];
}
